export const fieldConstants: Record<string, string> = {
  GET_NEXT_GENERATION: "GET_NEXT_GENERATION",
  GET_PREV_GENERATION: "GET_PREV_GENERATION",
  TOGGLE_CELL_ALIVE_STATUS: "TOGGLE_CELL_ALIVE_STATUS",
  INITIALIZE_FIELD: "INITIALIZE_FIELD",
  RESIZE_FIELD: "RESIZE_FIELD",
};
